### ISSUE TITLE
Fading out of QskSubWindow

### ISSUE THREAD

**Issue by uwerat** [uwerat/qskinny#10]
We need to find a way how to fade out QskSubWindow.

Classes derived from QskSubWindow are often dialogs and candidates for being created on the stack being processed in a recursive event loop. To solve this type of use case we might need to have some sort of "post mortem" handler grabbing the contents into an image or simply hijacking the scenegraph node subtree.

An obvious solution would be to let some sort of QskPopupManager let do the job.

**Comment by peter-ha** [comment]
Note to self: Looks like we need to make use of QskPopup's fadingChanged(), maybeQuit() etc. to check whether we are fading out.

**Comment by uwerat** [comment]
Done
