### ISSUE TITLE
QskComboBox

### ISSUE THREAD

**Issue by uwerat** [uwerat/qskinny#102]
A combo box is missing

**Comment by rick-vogel** [comment]
### Functional Requirements

- The selection must be scrollable
- The selection must be navigatable by moving the focus
- When opening the selection the currently selected item must be focused
- The selection must allow both images and text, only text or only images

### Ideas

- Make the height of the selection configurable / styleable e.g. `void setVisibleNumberOfItems(int x)` with `x * height of line edit`

### Visual
#### Minimalistic Inline Approach 

Similiar to e.g. MFC's ComboBox it should consist of a readonly textbox / lineedit / button plus a list that open below

![image](https://user-images.githubusercontent.com/111582062/218689260-c617bc23-69bf-496c-977a-f86e786a627b.png)

#### Virtual Keyboard

Similiar to iOS we could use the virtual keyboard for the value selection with the selection being scrollable 

![image](https://user-images.githubusercontent.com/111582062/218690821-1818a89f-a526-4eda-924a-5c7b2bd4708c.png)

#### Dropdown Selection Dialog

![image](https://user-images.githubusercontent.com/111582062/218691145-e8f59e1e-b7b2-4981-ae95-63fb8d6cc2fd.png)

**Comment by uwerat** [comment]
I would prefer to start with a minimalistic version of a combo box, that is not editable ( see https://doc.qt.io/qt-5/qcombobox.html#editable-prop ). The basic API should be similar to the other type of controls, that do a "one of several selection". Working on a common base class ( something like QskSelectorControl ) that can be used for QskMenu, QskSegmentadBar and QskComboBox, is on my TODO list for this week.

The default implementation delegates the actual selection to a QskMenu. However the API shall allow to customize the combo box to use a different type of popup ( see https://doc.qt.io/qt-5/qcombobox.html#showPopup ).

So in the end the initial implementation of the combobox has to display a graphic and/or text and a symbol ( see QStyle::SC_ComboBoxArrow ), do all the focus/keyboard handling and has some glue code for the popup menu.

**Comment by uwerat** [comment]
There is also a control called "tumbler": https://doc.qt.io/qt-6/qml-qtquick-controls2-tumbler.html

It is kind of overlapping with an editable combo box or a spin box and it is not so easy to decide if something like this should be its own type of control or a flavor of an existing one. My rule of thumb here would be to follow what Qt is doing.

**Comment by cathaychen** [comment]
So, when and how to implement it? a bad implementation is better than no implementation.

**Comment by peter-ha** [comment]
It is implemented, as this task here is closed with a linked commit. See the selectors tab of the gallery example:

![Screenshot from 2023-02-17 15-02-56](https://user-images.githubusercontent.com/1749504/220069148-066961b4-40c2-45b1-a7a3-43c3ee8270c4.png)

**Comment by cathaychen** [comment]
> 

thanks a lot.

in my computer, bewildered:
![combobox](https://user-images.githubusercontent.com/12231799/220228259-15274390-fed1-41d1-91e5-022b90a3ec01.png)

qt 6.4, windows 10 22h2, source code of 02/17/2023

**Comment by cathaychen** [comment]
OK, i download the newer source code, all is ok, thx
