### ISSUE TITLE
QskSwitchButton

### ISSUE THREAD

**Issue by uwerat** [uwerat/qskinny#108]
Something like https://doc.qt.io/qt-5/qml-qtquick-controls2-switch.html

**Comment by clemensmanert** [comment]
#121

**Comment by uwerat** [comment]
Hallo Clemens,

we are working on a Contributor License Agreement, and you might have to repeat the pull request once it is in place.

We want to be able to also publish qskinny under licenses like BSD/MIT at some point. The only reason why I have chosen the LGPL so far is, that in case we have to copy out code from the Qt libraries we do not run into legal conflicts. But so far this was not necessary and - fingers crossed - I hope it will never be.

But of course your contribution is very welcome and I will give you feedback.

**Comment by uwerat** [comment]
The pull request has been confirmed and we have a good start for this control now. I will spend some more time on the layout code, so that it becomes a bit more flexible.

Concerning the theming we could follow the specifications from here: https://material.io/components/switches.
The current implementation matches to some degree the IOS Look&Feel and could be used for the squiek skin. But we need some changes so that we are closer to the specification with the material style.

**Comment by uwerat** [comment]
Did some modifications to the layout and themeing code - squiek and material look different now. Still some way to go until it looks like in the specs.

The QAbstractButton::Checkable state creates a lot of confusion as it is no state and can't be en/disabled in almost all check buttons beside a regular push button. Something we need to get rid of.

**Comment by clemensmanert** [comment]
I need some time to checkout how the colors work in material and how the theme implementation matches these. But I'm on it.

**Comment by uwerat** [comment]
Great. I guess you might need to introduce more subcontrol ( f.e Panel ) so that you can solve problems like, that the thumb can be in outside of the track ( from the specs it looks like the center of the thumb is moving between the left/right or top/bottom positions  of the track ).

**Comment by clemensmanert** [comment]
How about #123? Works without a Panel.

**Comment by clemensmanert** [comment]
Can I rename the ColorPlate in the QskMaterial theme? The material definition names the colors surface, primary, secondary ... and it be easier to chose the right color for the nodes.

**Comment by uwerat** [comment]
The intention is, that the so called "material" skin matches the material specs, but at the moment we are not even close. So please go ahead: the closer we get to the specs the better.

**Comment by clemensmanert** [comment]
What do you mean with Thumb outside the Track? Do you mean it just laps over? This is possible with the current implementation.

**Comment by uwerat** [comment]
The center off the thumb is at the left/right/top/bottom end of the track, what means that the end of the thumb will be left/right/top/bottom by radius. Will have an effect on the sizeHint as well.
