### ISSUE TITLE
direct3d 11 support

### ISSUE THREAD

**Issue by ovenpasta** [uwerat/qskinny#164]
Qt 6.2.3 (x86_64-little_endian-llp64 shared (dynamic) release build; by GCC 11.2.0) on "windows"
OS: Windows 10 Version 1511 [winnt version 10.0.10586]

Architecture: x86_64; features: SSE2 SSE3 SSSE3 SSE4.1 SSE4.2 AVX AVX2

Here is a gdb session. Seems some problem with textures

```
(gdb) r
Starting program: E:\build-qskinny-master\examples\bin\automotive.exe
[New Thread 2176.0x2d68]
[New Thread 2176.0x2e84]
[New Thread 2176.0x25c4]
[New Thread 2176.0xc98]
[New Thread 2176.0x1728]
CTRL-S to change the skin.
CTRL-F to increase the font size.
CTRL-G to decrease the font size.
CTRL-B to enable visual debugging modes.
CTRL-K to dump statistics about the items/nodes being currently used.
CTRL-Q to terminate the application.
[New Thread 2176.0x1f68]
[New Thread 2176.0x2da8]
[New Thread 2176.0x27ec]
warning: Failed to create color buffer texture: Error 0x80070057: The parameter is incorrect.
warning: Failed to build or resize swapchain

Thread 9 "main" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 2176.0x27ec]
0x00007ffddd1a2ea1 in QSGOpaqueTextureMaterial::compare(QSGMaterial const*) const () from E:\build-qskinny-master\examples\bin\Qt6Quick.dll
(gdb) bt
#0  0x00007ffddd1a2ea1 in QSGOpaqueTextureMaterial::compare(QSGMaterial const*) const () from E:\build-qskinny-master\examples\bin\Qt6Quick.dll
#1  0x00007ffddd14939b in QSGBatchRenderer::Renderer::prepareOpaqueBatches()
    () from E:\build-qskinny-master\examples\bin\Qt6Quick.dll
#2  0x00007ffddd158c01 in QSGBatchRenderer::Renderer::prepareRenderPass(QSGBatchRenderer::Renderer::RenderPassContext*) ()
   from E:\build-qskinny-master\examples\bin\Qt6Quick.dll
#3  0x00007ffddd15b834 in QSGBatchRenderer::Renderer::render() ()
   from E:\build-qskinny-master\examples\bin\Qt6Quick.dll
#4  0x00007ffddd1633f4 in QSGRenderer::renderScene() ()
   from E:\build-qskinny-master\examples\bin\Qt6Quick.dll
#5  0x00007ffddd12a34c in QQuickWindowPrivate::renderSceneGraph(QSize const&, QSize const&) () from E:\build-qskinny-master\examples\bin\Qt6Quick.dll
#6  0x00007ffddd239292 in QSGRenderThread::syncAndRender() ()
   from E:\build-qskinny-master\examples\bin\Qt6Quick.dll
#7  0x00007ffddd23c9ce in QSGRenderThread::run() ()
   from E:\build-qskinny-master\examples\bin\Qt6Quick.dll
#8  0x00007ffde0f66342 in QThreadPrivate::start(void*) ()
   from E:\build-qskinny-master\examples\bin\Qt6Core.dll
#9  0x00007ffe00498102 in KERNEL32!BaseThreadInitThunk ()
   from C:\Windows\system32\kernel32.dll
#10 0x00007ffe019ac5b4 in ntdll!RtlUserThreadStart ()
   from C:\Windows\SYSTEM32\ntdll.dll
#11 0x0000000000000000 in ?? ()
Backtrace stopped: previous frame inner to this frame (corrupt stack?)
(gdb)
```

The crash does not happen with opengl backend enabled:
```
 export QSG_RHI_BACKEND=opengl 
```

**Comment by uwerat** [comment]
At the moment only OpenGL is supported. This has to do with the fact, that I was trying to avoid the overhead of instantiating a QSGTexture instance each time a texture needs to be rendered ( by using native OpenGL APIs ). But with the introduction of the Qt Rendering Hardware Interface it seems to be more or less mandatory to avoid problems like this one.

I will work on that problem next week, but I will need your support - I do not own any Windows system myself.

By the way: I will be able to work on QSkinny for the next months more or less full time. So you can expect a lot of improvements in the nearer future.

**Comment by uwerat** [comment]
Before continuing please check first if you are fine with contributor license agreement you find on the qskinny home page - you will have to sign it before you are able to create any pull request. The intention behind it is, that I'm planning to change the license to something like BSD once I'm sure I won't have to copy out Qt code.

Maybe we should have a chat on your topics before you continue - there are also other contributors with existing code that does overlap with what you have. If you contact me by Email I would arrange a meeting on Jitsi.

**Comment by uwerat** [comment]
I removed all OpenGL dependencies and replaced them by QRHI compliant APIs.

For creating textures the code explicitly checks if the current backend is OpenGL and only then it is creating the texture on the GPU ( using a FBO ). For all other backends there is no paint engine available and a QImage is created by the CPU and finally uploading to the GPU using QRHI compliant calls.

The experimental RHI implementation for Qt5 ( "export QSG_RHI=1" ) is not yet working. But as it was only for testing I probably won't work on this anymore.

As QskPaintedNode/QskGraphicNode are using QSGImage node now both work for the software backend as well.

Please give it a try and let me know if things are working on windows now.
