### ISSUE TITLE
issue with WorkerScript on msys2 mingw64

### ISSUE THREAD

**Issue by ovenpasta** [uwerat/qskinny#165]
running the examples that use qml hang

Qt 6.2.3 (x86_64-little_endian-llp64 shared (dynamic) release build; by GCC 11.2.0) on "windows"
OS: Windows 10 Version 1511 [winnt version 10.0.10586]
Architecture: x86_64; features: SSE2 SSE3 SSSE3 SSE4.1 SSE4.2 AVX AVX2

```
(gdb) r
Starting program: E:\build-qskinny-master\examples\bin\buttons.exe
[New Thread 7192.0x2bec]
[New Thread 7192.0x1bd0]
[New Thread 7192.0x296c]
[New Thread 7192.0x1ee0]
[New Thread 7192.0x2120]
CTRL-S to change the skin.
CTRL-F to increase the font size.
CTRL-G to decrease the font size.
CTRL-B to enable visual debugging modes.
CTRL-K to dump statistics about the items/nodes being currently used.
CTRL-Q to terminate the application.
[New Thread 7192.0x1110]
warning: QQmlApplicationEngine failed to load component
warning: qrc:/qml/buttons.qml: module "QtQml.WorkerScript" is not installed
```

**Comment by uwerat** [comment]
No clue - examples do work in my Linux environment. Could you please do some debugging in your environment ?

**Comment by ovenpasta** [comment]
I have both Linux and Windows machines but normally develop on Linux and deploy for Windows.
I don't know why gives that QQmlApplicationEngine warning and if it is related to the hanging at all.
I'll do some more investigation and report back.
