### ISSUE TITLE
QskMainView

### ISSUE THREAD

**Issue by uwerat** [uwerat/qskinny#173]
something like the application window in QML . Headers + central part + status bar

**Comment by peter-ha** [comment]
I guess this can be closed as implemented with 07e3cf7fd6d00c5a7a5745ebcd507d1896f706eb .

**Comment by uwerat** [comment]
Are these 95 lines really all what is needed for a main view ?
Anyway: should be good enough for a start and we can work on more details later.

But I will al least open a new issue for having at least basic QML support for QskApplicationView.
