### ISSUE TITLE
CI system: initial execution of a qskinny application

### ISSUE THREAD

**Issue by uwerat** [uwerat/qskinny#181]
Maybe it is possible to start a dummy QSkinny application and do some basic self tests after building on a certain platform ?

**Comment by peter-ha** [comment]
This is working on all platforms for Qt 5.15, see the screenshots below.

For Qt 6, it currently doesn't work on Windows: The Windows OS used by Github actions is Windows Server, whose OpenGL driver apparently is too old to be used with Qt.
Also, it seems more or less impossible to automatically install some Mesa OpenGL drivers in the system directory with Github Actions; Qt only looks in the system directory, and not in %PATH% or the executable directory.

I guess we have to live with this until we use the Direct 3D backend on Windows for Qt 6.

Interestingly, the apps start fine with Qt 6 on Windows 11; apparently the OpenGL driver shipped with Windows 11 is newer and works with Qt.

![screenshot-linux-qt5-15](https://user-images.githubusercontent.com/1749504/168855526-0fcbef6c-b665-4a4d-a7a1-66de123fedd6.jpg)
![screenshot-windows-qt5-15](https://user-images.githubusercontent.com/1749504/168855596-dc37da37-94a2-4adc-9260-b7f572464000.jpg)
![screenshot-macos-qt5-15](https://user-images.githubusercontent.com/1749504/168855700-3339b2be-aef5-494b-8291-1b89ea667e7e.jpg)

**Comment by peter-ha** [comment]
This issue here depends on #164 .
