### ISSUE TITLE
win10+msvc2017+Qt5.14.2 cannot run(debug error)

### ISSUE THREAD

**Issue by choujayyl** [uwerat/qskinny#183]
![image](https://user-images.githubusercontent.com/28703422/163801081-df916a96-b4d6-454d-a0ef-ea867d925531.png)

**Comment by uwerat** [comment]
I recently dropped support for Qt < 5.15, so you have to upgrade from Qt 5.14 - even if your problem should be unrelated.

But the error message is about Qt not being able to load its platform plugin, what is unrelated to QSkinny.
Are you sure about MSVC2017_32 bit - according to https://doc.qt.io/qt-5/supported-platforms.html only x86_64 seem to be officially supported.

**Comment by choujayyl** [comment]
OK. This  is qt creator issue that not load related dll. But screen display is abnormal.
![image](https://user-images.githubusercontent.com/28703422/163901278-8448eccc-0def-49e0-9706-a45ca4fae103.png)

**Comment by uwerat** [comment]
What happens, when you resize the window with the mouse ?

**Comment by choujayyl** [comment]
![image](https://user-images.githubusercontent.com/28703422/163953127-6b1e6bfe-7264-4be9-a5fa-349a33514c9a.png)
nothing happened
![image](https://user-images.githubusercontent.com/28703422/163953486-2501ee5b-e506-443c-bde5-4a753fd3bb0e.png)
some demo do not show anthing.

**Comment by uwerat** [comment]
Well let's stick with the anchors example as it shows the "right" content - only the layout is not calculated.

Could you please start the debugger and check why QskWindow::layoutItems() is not executed - or what goes wrong inside. As it is called in QskWindow::resizeEvent I would have expected, that something happens when resizing the window ?

**Comment by uwerat** [comment]
Might be fixed with https://github.com/uwerat/qskinny/pull/188
