### ISSUE TITLE
Material3 and device independent pixels

### ISSUE THREAD

**Issue by uwerat** [uwerat/qskinny#210]
In the Material specs we find metrics given in "dp" ( f.e icons as 24dp -> https://material.io/design/iconography/system-icons.html#grid-and-keyline-shapes ). "dp" stands for density independent pixels: https://en.wikipedia.org/wiki/Device-independent_pixel

According to https://developer.android.com/training/multiscreen/screendensities#TaskUseDP the formula for translating dp to device depending pixels seems to be: px = dp * (dpi / 160)

I created corresponding C++ user literals in QskMaterial3Skin.cpp and used them for the strutSize of the push button icons.

The calculatation in the literal needs to be verified and probably all values for the metrics need to be given in dp ?

**Comment by peter-ha** [comment]
@uwerat : Where is the code for the user literals for the DPs? It doesn't seem to be in master...

And I guess we can use QScreen::physicalDotsPerInch() to figure out the density "bucket" like MDPI, HDPI etc.

**Comment by uwerat** [comment]
Ah yes code is at the moment only in a local branch. It looks like this:

```
namespace
{
    // see: https://en.wikipedia.org/wiki/Device-independent_pixel
    inline qreal dpToPixels( long double value )
    {
        static qreal factor = -1.0;

        if ( factor < 0.0 )
        {
            factor = 1.0;

#if 0
            if ( const auto screen = QGuiApplication::primaryScreen() )
            {
                // is this calculation correct ? TODO ...
                factor = screen->logicalDotsPerInch() / 160.0;
            }
#endif
        }

        return value * factor;
    }

    inline double operator ""_dp( long double value )
    {
        return dpToPixels( value );
    }

    inline double operator ""_dp( unsigned long long int value )
    {
        return dpToPixels( value );
    }
}
```
