### ISSUE TITLE
The very next touch event gets lost inside a `QskDialog` started with `exec()` 

### ISSUE THREAD

**Issue by clemensmanert** [uwerat/qskinny#224]
When a touch event invokes the `QskDialog::exec()` the very next touch event gets lost. 

Example:
```C++
#include <QGuiApplication>

#include <QskWindow.h>
#include <QskPushButton.h>
#include <QskMessageSubWindow.h>

int main( int argc, char* argv[] )
{
    QGuiApplication app( argc, argv );
    QskWindow window;

    auto dialog = new QskMessageSubWindow(window.contentItem());
    dialog->setText("Close me with one touch");

    auto btnOpen = new QskPushButton("Open");
    auto btnClose = new QskPushButton("Close", dialog);
    
    QObject::connect(btnOpen, &QskPushButton::clicked,
		     dialog, &QskMessageSubWindow::exec);
    QObject::connect(btnClose, &QskPushButton::clicked,
		     dialog, &QskMessageSubWindow::close);

    window.addItem( btnOpen );
    window.resize( 800, 800 );
    window.show();

    return app.exec();
}
```

Touching the `btnOpen` opens the dialog, but the very next touch on close button inside the dialog is not recognized. This happens also to any other widget, which might be present. Any other touch event after gets processed as expected.

I suspect this is not a bug of qskinny itself, but of qquick. I tried to debug it for weeks and the only thing I came up with was a workaround #225, which might explain what is missing inside qquick.

**Comment by uwerat** [comment]
Should be a problem of the touch driver
