### ISSUE TITLE
Add skinnable storage page to IOT example

### ISSUE THREAD

**Issue by vrcomputing** [uwerat/qskinny#244]
![image](https://user-images.githubusercontent.com/6728289/210376626-0dc2b37d-c51b-41b9-8204-6092df54a2a4.png)

- [ ] add list of storages
- [ ] add occupancy bar for e.g. multi media files (music, pictures, ...)
- [ ] add storage capacity / occupancy values ( GiBi or % )

**Comment by peter-ha** [comment]
Has already been merged to master
