### ISSUE TITLE
box renderer: Alpha value is sometimes discarded for non-rectellipse shapes

### ISSUE THREAD

**Issue by peter-ha** [uwerat/qskinny#254]
This can be reproduced in the gallery by setting the segmented bar page to disabled:

When a control is in Minimum or Maximum state, the alpha value gets discarded.

This doesn't seem to be a problem in the box renderer itself, because in the normal case it is working. Maybe it has to do how we store the skin hints or so?

**Comment by uwerat** [comment]
The issue seems to be gone with the new implementation of the box renderer.
