### ISSUE TITLE
QskAspect: Introduce enum emphasis, variant or similar

### ISSUE THREAD

**Issue by peter-ha** [uwerat/qskinny#256]
Trying to get a common understanding of different skins like Material 3, Windows, iOS and Ubuntu (Vanilla), we might need controls with different emphasis or variants, e.g. important push buttons being more noticeable than less important ones.

This issue is to gather some feedback on how we want to proceed here.

## Controls that have different emhasis:

![Screenshot from 2023-02-02 14-29-22](https://user-images.githubusercontent.com/1749504/216352177-f93c9de7-28b4-4201-a025-b8cf5d6583d3.png)

![Screenshot from 2023-02-02 14-30-28](https://user-images.githubusercontent.com/1749504/216352223-2baf8321-5fae-4264-984d-760fdf09d037.png)

![Screenshot from 2023-02-02 14-31-01](https://user-images.githubusercontent.com/1749504/216352256-03109424-9556-498d-a520-a555c91771fb.png)

![Screenshot from 2023-02-02 14-31-22](https://user-images.githubusercontent.com/1749504/216352500-19af92c1-c47f-4d0c-8d85-e878154665b5.png)

![Screenshot from 2023-02-02 14-38-44](https://user-images.githubusercontent.com/1749504/216352565-55f02db6-372d-4f8a-a1dd-6b66a2e5cc38.png)

![Screenshot from 2023-02-02 14-53-04](https://user-images.githubusercontent.com/1749504/216352611-81c70682-dbba-4c84-9832-7034f6462ace.png)

![Screenshot from 2023-02-02 14-57-11](https://user-images.githubusercontent.com/1749504/216352671-5629cd3e-9e8b-45fa-bf32-740253f805a0.png)

## Controls that have different variants (that are different from a styling perspective):

- Material 3 buttons, FABs (see above) and icon buttons:

![Screenshot from 2023-02-02 15-34-51](https://user-images.githubusercontent.com/1749504/216353468-41ba8825-4f4f-4e9e-a4ab-556a3efc40e8.png)

- Material 3 Chips (?, see above): assist / filter / input / suggestion

![Screenshot from 2023-02-02 14-47-50](https://user-images.githubusercontent.com/1749504/216354058-400caa6c-3694-4dd3-b4fb-afab9faf027c.png)

**Comment by peter-ha** [comment]
I tried adding a new enum Emphasis to QskAspect, just to get a feeling for it: https://github.com/edelhirsch/qskinny/tree/m3

This seems to work nicely for the buttons:

![Screenshot from 2023-02-03 16-13-33](https://user-images.githubusercontent.com/1749504/216659193-4aded721-8caf-4eda-b3e5-c70ccd6eddde.png)

![Screenshot from 2023-02-03 16-57-14](https://user-images.githubusercontent.com/1749504/216659225-7537060f-db04-4d7f-8d9e-f70581fac90e.png)

Also at this point I am wondering whether the Section enum works out; my gut feeling is this is not exactly what we need for Material 3 at least, but let's see how this all plays out...

**Comment by uwerat** [comment]
see QskAspect::Variation
