### ISSUE TITLE
M3: focus indication

### ISSUE THREAD

**Issue by uwerat** [uwerat/qskinny#271]
The M3 skin does not support the focus indicator and therefore we need to have specific settings for the Focused state.
F.e. selecting a value of a QskSegmentedBar in the gallery is more or less impossible today.

**Comment by peter-ha** [comment]
Work has already been started here: https://github.com/edelhirsch/qskinny/tree/m3-segmented-bar-hovered , I will hopefully be able to continue from there in the next days...

**Comment by uwerat** [comment]
In earlier versions of QskSkin it was possible to set a stateMask to disable all states, that are not supported by a skin.

But such a mask is probably more useful as runtime setting depending on the hardware setup. F.e. when having touch only there is not much sense in handling/displaying Hover/Focused states.

On the implementation side it might be possible to apply the state mask inside of effectiveSkinHint.
