### ISSUE TITLE
Windows themeing

### ISSUE THREAD

**Issue by uwerat** [uwerat/qskinny#284]
For the initial release of QSkinny we want to have at least 2 themes/skis to demonstrate the theming concepts. One of the skins should be for a mobile and the other for a desktop environment.

For mobile we already have the Material3 skin - for the desktop we implement the Windows specifications.
Once we have something working we can remove the Squiek skin, that is used as placeholder for a desktop theme so far.

**Comment by peter-ha** [comment]
For the first version, I think I am done. Let me know if something is still missing...
