### ISSUE TITLE
Material design or other "pretty" example

### ISSUE THREAD

**Issue by jcelerier** [uwerat/qskinny#29]
Hi, stumbled on your library from a comment on a blog post.
The intent is very good (in my opinion, such a library is necessary!), however I think that the examples's graphical style really don't do justice to the potential of this library (the gradients! gosh) which would in turn lead to less users, thus less eyes on the code and bugs found.

Why not taking the visual style of, for instance, Qt Quick Controls {1,2}'s style ? 
Or one of the UI guidelines given here ? https://github.com/ioncodes/awesome-ui 
Taking inspiration from Kirigami UI ? https://dot.kde.org/sites/dot.kde.org/files/Desktop.png
There is also a QtQuick Controls 2 style that allows taking the colors of the system theme: https://cgit.kde.org/scratch/mart/desktopqqc2style.git/ 
couldn't something similar be leveraged to give the apps a style that at least fits a desktop ?

Thanks for the work in all cases, I hope that something like this will be merged into qt eventually

**Comment by uwerat** [comment]
QSkinny is part of an ongoing development for a really big user interface, that is implemented to 100% in C++.  It has well defined skins ( = themes ) and would be a great demonstration of what is  already possible.

Unfortunately I can't show this code, but to summarize our experience so far:

- the existing skin system could be customized to look like requested from our UI designers
- startup performance is a non issue, the user interface is "instantly" on screen

My priorities at the moment are still on solving technical issues and not so much on fine tuning the visual appearance. I'm also not yet finally satisfied with the APIs for customizing the skins - it is very flexible but not that easy to understand.

The skins and "examples" you see in the repository are more or less intended to have something for the moment to support the development. But I hope I will be able to come up with some sort of first release end of this year and of course this one has to include at least two skins with an acceptable appearance.

**Comment by uwerat** [comment]
see gallery

**Comment by jcelerier** [comment]
fantastic work!
