### ISSUE TITLE
Screenshot

### ISSUE THREAD

**Issue by rpasichnyk** [uwerat/qskinny#32]
Can you please add screenshot to README?
I think this one is quite nice
https://pbs.twimg.com/media/DFguVReXkAAOQqc.jpg

**Comment by peter-ha** [comment]
Thanks for the suggestion, pull request made at https://github.com/uwerat/qskinny/pull/33

**Comment by uwerat** [comment]
I enabled the raster paint engine being used for creating the textures from svg/qvg graphics in the automative example. The result is simply better and surprisingly rendering seems to be also faster for the use case of simple SVGs

Peter could you please post another pull request with a new screenshot made with these changes ?
