### ISSUE TITLE
QStyleHints

### ISSUE THREAD

**Issue by uwerat** [uwerat/qskinny#320]
Can we make more use of what we get from https://doc.qt.io/qt-6/qguiapplication.html#styleHints ?

F.e since Qt 6.5 there is https://doc.qt.io/qt-6/qstylehints.html#colorScheme-prop, that could be used to initialize the skin with a dark/light setup.

**Comment by peter-ha** [comment]
If you want I can look into this, feel free to assign it to me...

**Comment by peter-ha** [comment]
On Ubuntu QStyleHints respects the Light / Dark color scheme, so this sounds worthwhile to have for us as well.

I guess we can also look into using mousePressAndHoldInterval etc.?
