### ISSUE TITLE
No targets specified and no makefile found

### ISSUE THREAD

**Issue by Husenjon** [uwerat/qskinny#341]
I installed according to the manual
PREFIX=/opt/qskinny qmake -r 
i use qt6

**Comment by uwerat** [comment]
tutorials/03-writing-your-first-application.asciidoc needs to be adjusted for using cmake

**Comment by thewake** [comment]
The following commands worked for me:
```
cmake -DCMAKE_BUILD_TYPE=Debug -DCMAKE_MAKE_PROGRAM=path/to/ninja -DCMAKE_INSTALL_PREFIX=/path/to/install -G Ninja
```
```
ninja
```
```
ninja install
```

**Comment by uwerat** [comment]
documentation has been updated
