### ISSUE TITLE
Maybe you can write a new “Writing your first application” with the windows environment？

### ISSUE THREAD

**Issue by anvalue** [uwerat/qskinny#368]
Maybe you can write a new “Writing your first application” with the windows environment？
i am a new Qt amateur, i very want to use QSkinny, but i can start！would you mind to write a qtcreator using QSkinny（Windows）？

**Comment by lgtmak** [comment]
If you are referring to: https://qskinny.github.io/docs/tutorials/03-writing-your-first-application/

Then this information is outdated. A more up-to-date version can be found in the `master` branch in the file: [doc/tutorials/03-writing-your-first-application.asciidoc](https://github.com/uwerat/qskinny/blob/master/doc/tutorials/03-writing-your-first-application.asciidoc)

This is updated to have the build process for CMake which you should be able to use in a Windows environment. For generating a binary for windows you can review the `examples` directory build file.

I also found an issue with some of the sample code in the "Writing your first application", for Fluent2 (Windows-style skin) you need to call `setPanel( true )` on the `horizontalBox` (ex. `horizontalBox.setPanel( true );`), the code to fix that can be found in a PR here: https://github.com/uwerat/qskinny/pull/364/files#diff-1719cc6660549bef08b660ac3e40ad202a0dfeff1a3958a044a35208ab8ef308R125

**Comment by anvalue** [comment]
> If you are referring to: https://qskinny.github.io/docs/tutorials/03-writing-your-first-application/
> 
> Then this information is outdated. A more up-to-date version can be found in the `master` branch in the file: [doc/tutorials/03-writing-your-first-application.asciidoc](https://github.com/uwerat/qskinny/blob/master/doc/tutorials/03-writing-your-first-application.asciidoc)
> 
> This is updated to have the build process for CMake which you should be able to use in a Windows environment. For generating a binary for windows you can review the `examples` directory build file.
> 
> I also found an issue with some of the sample code in the "Writing your first application", for Fluent2 (Windows-style skin) there is a bug where you need to call `setPanel( true )` on the `horizontalBox` (ex. `horizontalBox->setPanel( true );`), the code to fix that can be found in a PR here: https://github.com/uwerat/qskinny/pull/364/files#diff-1719cc6660549bef08b660ac3e40ad202a0dfeff1a3958a044a35208ab8ef308R125

Thanks a lot

**Comment by uwerat** [comment]
Of course it is a disaster, that the home page shows outdated information. We have to solve this somehow.
