### ISSUE TITLE
Webassembly

### ISSUE THREAD

**Issue by uwerat** [uwerat/qskinny#372]
Is it possible to run QSkinny applications on the Webassemby platform: https://doc.qt.io/qt-6/wasm.html

**Comment by peter-ha** [comment]
![Screenshot from 2024-01-19 13-47-36](https://github.com/uwerat/qskinny/assets/1749504/cb754c0b-10c8-4e93-999e-5d62ca125d2b)
![Screenshot from 2024-01-19 09-21-47](https://github.com/uwerat/qskinny/assets/1749504/7226de3c-fc52-4693-b046-c31daef3cc2d)
![Screenshot from 2024-01-19 09-21-29](https://github.com/uwerat/qskinny/assets/1749504/e63d2712-83a3-4a08-a2f2-8c0f06ba523a)
![Screenshot from 2024-01-19 09-21-22](https://github.com/uwerat/qskinny/assets/1749504/94fe7774-414f-4d8d-90e9-a48c3db85db1)
![Screenshot from 2024-01-19 09-21-07](https://github.com/uwerat/qskinny/assets/1749504/e03e9578-ccc9-4cf6-99eb-6a9c2f60c57c)
