### ISSUE TITLE
QskSpinBox Buttons for Material3

### ISSUE THREAD

**Issue by uwerat** [uwerat/qskinny#398]
Material3 does not have any spin boxes and we do not have a specification how to display it.

However other toolkits supporting Material3 display the buttons in a different way as we do at the moment:

- https://www.qt.io/blog/material-3-changes-in-qt-quick-controls
- https://pub.dev/packages/flutter_spinbox

As long as we do not know better we should align our implementation with what others are doing:

- The Up/Down buttons should use '-'/'+' symbols
- The Up/Down buttons should look like a QskPushButton with  QskPushButton::VeryLowEmphasis

**Comment by peter-ha** [comment]
I guess this issue can be closed now that the corresponding PR has been integrated as well, see the commits in the comment.
