### ISSUE TITLE
WebAssembly Support

### ISSUE THREAD

**Issue by nacertnsi** [uwerat/qskinny#403]
does qskinny support WebAssembly?

**Comment by uwerat** [comment]
Yes - see https://gist.github.com/peter-ha/4096020518f9da39b2d70b2c406f8820.

The issues in the source code have been fixed. However we ( @peter-ha ) did not improve the cmake files yet, so that static linkage works without the hacks that @peter-ha had to do.

**Comment by peter-ha** [comment]
I just checked: This works on master as well, the cmake files adjustments have also been merged (63cb58ef4aadf57be3a393a8f9630c61691f29e9).

**Comment by uwerat** [comment]
@peter-ha Does it make sense to summarize the build steps as tutorial in doc/tutorials ?

**Comment by peter-ha** [comment]
Ah yes, I was sidetracked by the whole documentation topic but I can write up the steps first, will post here when I've done that

**Comment by uwerat** [comment]
Concerning the problem with recursive eventloops ( a.k.a QDialog::exec ): I  added a workaround in the example. The final solution will be implemented here: https://github.com/uwerat/qskinny/issues/404

@peter-ha: do you have any clue about the qvg file warnings ?

**Comment by peter-ha** [comment]
No, I haven't investigated the QVG warnings, I didn't notice them earlier I have to say...

**Comment by peter-ha** [comment]
How to build QSkinny for WebAssembly has been documented on the home page -> https://qskinny.github.io/docs/tutorials/11-How-to-build-for-Wasm/
