### ISSUE TITLE
Wasm: Icons are not displayed correctly in gallery

### ISSUE THREAD

**Issue by peter-ha** [uwerat/qskinny#409]
There are 2 problems here:

1. Icons from design systems are not loaded at all; this is due to a `Q_INIT_RESOURCE` call missing
2. Icons in the gallery are not drawn correctly; which is weird, because e.g. in the IOT dashboard they are displayed correctly

**Comment by peter-ha** [comment]
Regarding the 2nd issue from above:

The reason why the IOT dashboard is displaying the icons correctly and the gallery doesn't is because in the IOT dashboard we draw our textures with the raster mode (`QskSetup::setUpdateFlag( QskItem::PreferRasterForTextures, true );`.

I am not sure if we want to detect the Wasm platform and default to raster or so, or if there is a better solution...

**Comment by uwerat** [comment]
Using the raster mode as default makes sense - at least for small icons. The quality of the antialiasing is better and filling the pixels isn't much more expensive than the tesselation. IIRC my performance tests ( should be in the history of the git repository ) with loading tons of small icons showed the raster path being slightly faster ( Qt 5.4 at that time ).

However using the raster paint engine seems to be a workaround for a general problem that might have to do with the availability of FBOs. Maybe we have to do some additional checks: https://doc.qt.io/qt-6/qopenglfunctions.html#openGLFeatures ?

**Comment by peter-ha** [comment]
These are the OpenGL functions that are available on desktop and not on Wasm; to me it doesn't look like we are using those, but maybe I just don't know the code well enough:

```
QOpenGLFunctions::NPOTTextures
QOpenGLFunctions::NPOTTextureRepeat
QOpenGLFunctions::FixedFunctionPipeline
QOpenGLFunctions::TextureRGFormats
QOpenGLFunctions::MultipleRenderTargets
QOpenGLFunctions::BlendEquationAdvanced
```
