### ISSUE TITLE
 QskSimpleListBox has a problem 

### ISSUE THREAD

**Issue by hestrro** [uwerat/qskinny#418]
Thank you for your last answer

The removeAt() function of QskSimpleListBox cannot remove the specified content
It was found that there was an incorrect judgment condition when removing
    if ( m_data->columnWidthHint <= 0.0 )
    {
        const auto w = qskHorizontalAdvance( effectiveFont( Cell ), entries[ index ] );
        if ( w >= m_data->maxTextWidth )
            m_data->maxTextWidth = qskMaxWidth( effectiveFont( Text ), entries );
    }
    else
    {
        entries.removeAt( index );
    }

I think else here is redundant

**Comment by uwerat** [comment]
s/redundant/wrong : fixed, thanks for reporting
