### ISSUE TITLE
qquickitem display problem

### ISSUE THREAD

**Issue by hestrro** [uwerat/qskinny#421]
How should I display a custom image that inherits qquickitem in qskwindow? Should I additem directly?

**Comment by hestrro** [comment]
Are there similar concepts of view, scene, and item?

**Comment by uwerat** [comment]
Guess by "custom image" you mean a QImage you have rendered using QPainter - you can use QskGraphic then.

Note, that QskGraphic is a paint device itself and you might not need the QImage. When drawing your content directly to it the result will be scalable.

There are various ways how to display a QskGraphic as a texture on the scene graph. The most simple one is to use a QskGraphicLabel.

**Comment by hestrro** [comment]
Thank you, I think I found what I want, I want to draw an roi by dragging with the mouse, such as rectangle, circle, concentric circle, etc. I found that qskGraphic can accept a qpainterpath parameter, this should help I achieve the desired effect

**Comment by uwerat** [comment]
QskGraphic graphic;

QPainter painter(  &graphic );
painter.setPen( ... );
painter.setBrush( .. );
painter.drawXXX( ... );
...
