### ISSUE TITLE
support problem

### ISSUE THREAD

**Issue by hestrro** [uwerat/qskinny#424]
After cmake compiled the package and install generated the bin, include, and lib files, I didn't find the support dll and header files in it, so I couldn't use the contents. I checked the cmakelist file and found that you didn't write it. Related to the import directive, I think this might be a bug

**Comment by uwerat** [comment]
Did you follow the steps of the tutorial: https://github.com/uwerat/qskinny/blob/master/doc/tutorials/03-writing-your-first-application.asciidoc ?

**Comment by hestrro** [comment]
I followed the steps here to generate the bin, lib, and include files. I compiled them with qt 6.5.3 in a windows environment.

**Comment by uwerat** [comment]
I checked the installation on my Linux box - actually I do not have any Windows system at all.
Here the installation ended up with the following tree ( setting qsk as root ):

qsk
qsk/bin
qsk/include
qsk/include/qskinny
qsk/lib
qsk/lib/qskinny
qsk/lib/qskinny/plugins
qsk/lib/qskinny/plugins/skins
qsk/lib/qskinny/plugins/platforminputcontexts
qsk/lib/cmake
qsk/lib/cmake/QSkinny
qsk/lib/cmake/QSkinny/scripts

The include files are below qsk/include/qskinny, the libraries below qsk/lib/qskinny.

What is the situation on your box ?

**Comment by hestrro** [comment]
My file structure is the same as yours, but there are no header files such as qsktestsupport.lib and SKinnyShortcut.h

**Comment by uwerat** [comment]
Both files belong to the examples that are not installed.

I agree, that we should have an option that allows the user to force the installation of the example executables. However this would only cover qsktestsupport.lib - not SkinnyShortcut.h.

Using the classes of the support directory in application code is like copying code from the examples. Perfectly o.k. to do so, but not covered by the installation process - by intention.
