### ISSUE TITLE
Having trouble using QskShapeNode and QskStrokeNode

### ISSUE THREAD

**Issue by hestrro** [uwerat/qskinny#429]
When I use QskShapeNode and QskStrokeNode，I would run into an Exception triggered issue causing the program to crash

What went wrong： node->updateNode(path,QTransform(),QRectF(0,0,100,100),QskGradient());

I debug traced  D:\QT\6.5.3\msvc2019_64\include\QtCore\qscopedpointer.h
   T *get() const noexcept
    {
        return d;
    }
What should I pay attention to when using these two nodes?

QSGNode *CustomItem::updatePaintNode(QSGNode *oldNode, UpdatePaintNodeData *updatePaintNodeData)
{
    QskShapeNode *node = static_cast<QskShapeNode *>(oldNode);
    if(!node)
    {

    pen.setColor(QColor(173, 216, 230));
    QPainterPath path;
    path.addRect(0,0,100,100);
    node->updateNode(path,QTransform(),QRectF(0,0,100,100),QskGradient());
    }
    return node;
}

**Comment by uwerat** [comment]
Maybe the shape node is not your paint node - you could do a dynamic_cast to check this.

In general the scene graph API of Qt/Quick is not very convenient and you have to fiddle around for finding the proper position of the node you want to modify. That' why we have these node roles in QSkinny code.

I recommend to inherit from QskControl where the framework inserts a item root node as paint node. Then the custom nodes can be inserted/found using the node roles. Actually I would recommend to copy and adjust the ShapeItem class from the shapes example.

Please note, that the theming concept of QSkinny works with skins, that provide specific skinlets that are responsible for creating the child nodes. Usually the skinlet is tied to the control from the skin, but it is also possible to assign your skinlet manually ( f.e in the charts example.
