### ISSUE TITLE
QskGraphicLabel position problem

### ISSUE THREAD

**Issue by hestrro** [uwerat/qskinny#430]
Can QskGraphicLabel only use setAlignment to adjust its position, and cannot use something like setGemometry to set its x, y coordinates?

**Comment by uwerat** [comment]
Check its base classes, QskItem and QQuickItem.

**Comment by hestrro** [comment]
Thank you, I missed writing this sentence
setPlacementPolicy(QskPlacementPolicy::Ignore);

**Comment by uwerat** [comment]
The placement policy is an information for a parent, that takes care of the geometries of its children ( usually a layout ).
QskPlacementPolicy::Ignore means that the layout should not take care of the geometry of a particular child.

Then you have to assign the geometries of this child manually - see above ...
