### ISSUE TITLE
Material 3 font sizes

### ISSUE THREAD

**Issue by uwerat** [uwerat/qskinny#432]
The initialization of the M3 fonts defines the sizes in "pt". The implementation converts "pt" to "px" and finally to pixels.
The second conversion uses qskDpToPixels instead of qskPxToPixels, what is probably wrong.

However without having a dp value in the conversion chain we won't have the density steps implemented in qskRoundedDpi ( QskPlatform.cpp ). So we might have to convert "pt" into "dp" instead of "px".

When doing this modification the fonts are obviously too big, what leads to 2 possible conclusions:

a) The initial sizes are not in "pt"
b) The implementation of qskDpToPixels is wrong

- https://www.w3.org/TR/css3-values/#absolute-lengths
- https://en.wikipedia.org/wiki/Device-independent_pixel
- https://developer.android.com/training/multiscreen/screendensities

**Comment by peter-ha** [comment]
To me it looks like Qt renders fonts bigger than M3 implementations, i.e. flutter (and possibly others).

When setting the font size to 200pt, Qt differs a lot from Skia, which is used internally in flutter:

![Screenshot from 2024-10-24 14-41-19](https://github.com/user-attachments/assets/63ad4efc-9122-43f0-92b6-c1a6fe339c0c)

I also verified that the fonts used in flutter are actually in pt, the flutter API is not very clear about this, but Skia is: https://api.skia.org/classSkFont.html#a7e28a156a517d01bc608c14c761346bf says "Constructs [SkFont](https://api.skia.org/classSkFont.html) with default values with [SkTypeface](https://api.skia.org/classSkTypeface.html) and size in points."

Qt renders fonts ~ 1.3x bigger than Skia, which happens to be roughly the same as the factor we get from our conversion, which seems to be only a coincidence.

I don't have a good solution to this problem though, other than accepting the difference and hardcoding it somewhere for us.

**Comment by uwerat** [comment]
Maybe the difference is because the given font sizes are sp -not dp - values. sp ( = scalable pixels ) are additionally scaled with a factor from the user settings:

- https://m2.material.io/design/layout/pixel-density.html#pixel-density-on-android.
- https://support.google.com/accessibility/android/answer/11183305?hl=en

IIRC there is something similar for Fluent2.

I already created https://github.com/uwerat/qskinny/issues/389 for this feature.

**Comment by uwerat** [comment]
After checking the specs I'm wandering whether the font sizes are indeed in dp - when interpreting them as pt the results look much more reasonable. So let's do this
