### ISSUE TITLE
QskGraphic's toImage(size,Qt::KeepAspectRatio,1) problem

### ISSUE THREAD

**Issue by hestrro** [uwerat/qskinny#436]
When I read the jpg image format and convert it, there will be no loss of pixels, but there will be a loss in the png image format. What do I need to do to convert png without loss?
 //image
    QImage originalImage("C:/Users/W000670/Desktop/QskControl.jpg");
    QSize size=originalImage.size();
    QskGraphic graphic1=QskGraphic::fromImage(originalImage);
    auto processedImage=graphic1.toImage(size,Qt::KeepAspectRatio,1);

    if (originalImage.size() == processedImage.size()) {
        for (int y = 0; y < originalImage.height(); ++y) {
            for (int x = 0; x < originalImage.width(); ++x) {
                if (originalImage.pixel(x, y) != processedImage.pixel(x, y)) {
                    qDebug() << "Pixel loss detected at" << x << y;
                    qDebug() << "Pixel originalImage" << originalImage.pixel(x, y);
                    qDebug() << "Pixel processedImage" <<processedImage.pixel(x, y);
                }
            }
        }
    } else {
        qDebug() << "Images have different sizes";
    }

**Comment by uwerat** [comment]
QSkinny is designed to work with scalable ( vector ) image formats and I recommend to use one of them - if possible.
Questions about specific image fomats is out of scope here - please contact the related channels.
