### ISSUE TITLE
inputpanel problem

### ISSUE THREAD

**Issue by hestrro** [uwerat/qskinny#438]
Can the input panel not display the virtual keyboard and only display predictive text? How to do it?

**Comment by uwerat** [comment]
The "code once, run everywhere" concept of Qt means, that an application has to run on environments with touch screen and/or devices with keyboard or other input devices. To make this possible the Qt development introduced input methods - see f.e https://www.kdab.com/qt-input-method-depth - that are loaded as plugins at runtime.

The virtual keyboard of QSkinny is available as such a plugin. It will be loaded when setting "QT_IM_MODULE=skinny". However - loading Qt plugins can be tricky as they need to be installed properly and they might be silently ignored, when dynamic linkage fails. I recommend to set "QT_DEBUG_PLUGINS=1" to have some information about what is going on behind the scenes.
