### ISSUE TITLE
QskMenu ico problem

### ISSUE THREAD

**Issue by hestrro** [uwerat/qskinny#442]
When I downloaded some icos in svg format, converted them to qvg, and added them through the addOption function of QskMenu, the icos became very small and could not be seen clearly, but they became larger when used with your QSkinny qvg resources. How did you get your ico resources?

**Comment by uwerat** [comment]
SVGs are scalable and you should be able to display them in any size. However your icons might have a viewBox that adds margins. So you can try to remove it from your SVG with a text editor.

In case you want to increase the size of the icons you can try: menu->setStrutSizeHint( QskMenu::Icon, ... )

**Comment by hestrro** [comment]
Thank you, my problem is solved。Do you have any ideas about the secondary menu of Qskmenu?

**Comment by uwerat** [comment]
QSkinny was started 2016 as the platform for a huge automotive project. While this project reached the market several years ago we never found the time to publish a stable release of the open source part.  For the next months this release will be our focus - however cascading menus is not planned to be part of it.

Of course contributions can always be submitted and might make it into that release.

In case there is a company behind your project: you can shift priorities by sponsoring certain features or hiring one of the core developers to get the task done.

**Comment by hestrro** [comment]
Thanks, I'll think about it

**Comment by uwerat** [comment]
I opened the https://github.com/uwerat/qskinny/discussions section. Please use it for support requests.
