### ISSUE TITLE
circle button problem

### ISSUE THREAD

**Issue by hestrro** [uwerat/qskinny#447]
I want to create a round button with only ico. When the length and width are less than 48, the ico of the button will be offset from the center. Can this be solved?

auto shapeButton3=new QskPushButton(this);
        shapeButton3->setIconSource("sports_soccer");
        shapeButton3->setPlacementPolicy(QskPlacementPolicy::Ignore);
        shapeButton3->setGeometry(250,320,40,40);
        auto metric3=new QskBoxShapeMetrics(20,20,20,20);
        shapeButton3->setShape(*metric2);

**Comment by uwerat** [comment]
I enabled the discussions ( https://github.com/uwerat/qskinny/discussions ) section yesterday. Please use this section for support requests.
