### ISSUE TITLE
QskTextInput wrapmode

### ISSUE THREAD

**Issue by uwerat** [uwerat/qskinny#451]
QskTextInput is a wrapper for QQuickTextInput often simply duplicating its API. Looks like the wrap mode ( https://doc.qt.io/qt-6/qml-qtquick-textinput.html#wrapMode-prop ) has been forgotten so far.

The corresponding enum can be found in QskTextOptions

**Comment by hestrro** [comment]
But it does not have the QskTextOption related function for setting the sub-control text like QskTextLabel, and I did not find it in its parent class.

**Comment by hestrro** [comment]
I can only set wrapword in its source code

**Comment by uwerat** [comment]
Sure, the wrapper for the API is missing - that's why this issue exists. Note that the fix will part of the release ( see the Milestone label )

**Comment by uwerat** [comment]
Done
