### ISSUE TITLE
QskTextField‘PlaceholderText

### ISSUE THREAD

**Issue by hestrro** [uwerat/qskinny#486]
![image](https://github.com/user-attachments/assets/4a20ffb1-8a4d-4125-b4c4-961bf4701c1c)
When setPlaceholderText("please edit"); is called, I click and then enter, the PlaceholderText does not disappear immediately, and overlaps with the text being entered. I feel that this affects the experience

**Comment by uwerat** [comment]
QskTextEdit is work i progress - hope I will have a first "final" version of it end of next week.

**Comment by uwerat** [comment]
fixed
