### ISSUE TITLE
How to build this source code on Windows 7 VS2015 by Qt5.10.1?

### ISSUE THREAD

**Issue by toby20130333** [uwerat/qskinny#64]
Hi @uwerat 
I want to build this project by qt5.10.1 on Windows 7 with VS2015
but I got a lots of build error.
So It can be build on Windows? or cross platform?

**Comment by uwerat** [comment]
qskinny is supposed to work on any platform where you can run Qt/Quick >= 5.6.

But as the project driving this framework is based on linux I never tried anything else than gcc/clang compilers so far.

But it should be no big deal to fix any compiler incompatibilities. Please contact me directly by Email with more details.

**Comment by uwerat** [comment]
As there is no further information provided I'm closing this issue without being resolved.
