### ISSUE TITLE
ASSERT: "m_data->skin" in file ../skinny_test/libs/QSkinny/src/controls/QskSetup.cpp, line 225

### ISSUE THREAD

**Issue by LinArcX** [uwerat/qskinny#76]
Hi. i want to embed the source code of this library into my project. so i picked up only:
1. qmlexport
2. skins
3. src
4. support
Directories, fix the header paths and try to compile my project.
But i get an error:
```
ASSERT: "m_data->skin" in file ../skinny_test/libs/QSkinny/src/controls/QskSetup.cpp, line 225
13:01:43: The program has unexpectedly finished.
13:01:43: The process was ended forcefully.
```
And this is skin() method in QskSetup.cpp file:
```
QskSkin* QskSetup::skin()
{
    if (m_data->skin == nullptr) {
        m_data->skin = QskSkinManager::instance()->createSkin(QString());
        Q_ASSERT(m_data->skin);

        m_data->skin->setParent(this);
        m_data->skinName = m_data->skin->objectName();
    }

    return m_data->skin;
}
```
in line: ` Q_ASSERT(m_data->skin);` it throws an error and program stop to working.
Seems it loop up for skins in a file called: `metadata.json`, right?
Line 15 of file __QskSquiekSkinFactory.h__:
`Q_PLUGIN_METADATA(IID QskSkinFactoryIID FILE "metadata.json")`
As i changed all paths in my project, it seems that it can't read this file. i don't know why.
I also use absolute path in my computer:
`/mnt/D/Document/WorkSpace/Qt/Test/skinny_test/libs/QSkinny/skins/squiek/metadata.json`
But it fails again.

**Comment by uwerat** [comment]
You don't need the files from support, these are helper classes for the examples only. qmlexport is only required if you want to write your application in QML. For a pure C++ application you would not need this too.

You need to have at least one working skin, to get something going. But it is not necessary to load skins as plugins. All what needs to be done is to implement a QskSkinFactory, that creates your skin and to register it this way:

    qskSkinManager->setPluginPaths( QStringList() ); // no plugins
    qskSkinManager->registerFactory( "Skins", new MySkinFactory() );
    qskSetup->setSkin( "MySkin" ); // MySkinFactory knows what to do for "MySkin"

Note, that the skins you find in qskinny/skins are pretty poor. In the application driving the application of qskinny we have much better looking skins, but I'm not allowed to release them as open source. Hope I find the time to create more appealing skins for the open source path in the next months - what includes finding a more convenient way to implement them.
