### ISSUE TITLE
Why?

### ISSUE THREAD

**Issue by jhihn** [uwerat/qskinny#82]
I saw the Qt summit presentation but I still don't understand why this exists. Do you have any kind of benchmarks in terms of memory or performance? How does it compare to the standard QML stuff?

The styling might be nice, but I don't see that as the main focus of this effort?

**Comment by uwerat** [comment]
Did you never ask your self why the Qt development has thrown away QuickControls 1 ( QML ) and started with an implementation from scratch in C++: QuickControls 2. Of course this has to do with all the heaviness, that comes with QML. But all arguments, that lead to the decision to do the implementation in C++ are also true for application code. And this is the major design flaw of QC2: it does not allow to be used from C++. QSkinny gives you the option to make a conscious decision about where and when to use QML - including the option not to use QML at all.

The application behind QSkinny ( you only see a subset ) is a user interface of > 400K lines of GUI code - having the controls being implemented in C++ does not help much then, as it is is only a small subset of the overall code base.

The choice this specific application has made is 100% C++ - one of the main reason was, that the team working on the code was coming from Qt/Widgets and they could start effectively from day 1. Furthermore older projects do not go away and maintaining several generations of a product is much easier, when technologies are similar.

While using QML is a nice language for setting and binding properties it is not that cool, when it comes to binding data, that does not fit into what can be expressed by the meta object system. You end up with writing trillions of lines of boiler plate code to break the language barrier - usually by writing models. It is way more convenient to connect data and controls on the C++ level and expose only the rest to QML. Also declarative language is missing basic concepts like overloading - simply look at what type of construction are necessary to translate overloading an event handler into something you can do in QML. 

And of course: with QML your application runs a virtual machine, you don't have control over the memory management ( when are things created/deleted ), It is a homebrew system where you are not even close to the tool chain you find when using a standard language ( debugging, profiling, ... ).

Last but not least: once you have decided to do your own framework, you start with making decisions about things you have always been missing from the standard solution. A proper layout system, better themeing, support for vector graphics images, scene graph node composition and many more falls into this category.

**Comment by jhihn** [comment]
Thank you for that very informative reply!
