### ISSUE TITLE
interfaces for QHoverEvent isn't changed in Qt5.14.0 or above

### ISSUE THREAD

**Issue by DisableAsync** [uwerat/qskinny#87]
In [QskEvent.cpp](https://github.com/uwerat/qskinny/blob/master/src/controls/QskEvent.cpp#L75) we have this version check
```
QPointF qskHoverPosition( const QHoverEvent* event )
{
#if QT_VERSION >= QT_VERSION_CHECK( 5, 14, 0 )
    return event->position();
#else
    return event->posF();
#endif
}
```

But i just checked Qt docs, the interfaces for QHoverEvent is not changed, it's still `QHoverEvent::posF()`;
[Qt 5.14](https://doc-snapshots.qt.io/qt5-5.14/qhoverevent.html) [Qt 5.15](https://doc.qt.io/qt-5/qhoverevent.html) [Qt 6](https://doc-snapshots.qt.io/qt6-dev/qhoverevent.html)

Sorry im just too lazy to do commits, so ima just open an issue here.

**Comment by uwerat** [comment]
Ah yes it is a Qt6 change. Fixed.
