### ISSUE TITLE
ANGLE support

### ISSUE THREAD

**Issue by ovenpasta** [uwerat/qskinny#89]
I'm having problems with the windows platform as a target (QT 5.15.2 - MXE - x86_64). (Linux target works as expected)

- If I use `QT_OPENGL=desktop` the graphics are being rendered properly, but the fonts are messed up (random artifacts)
- If I use `QT_OPENGL=angle` the graphics are not rendered (black rectangles) but the fonts are rendered properly.

I'd like to use the angle backend since I cannot rely on target opengl drivers
I think there has to be something related with the qskinny texture code. The problem happens both for raster images and qvg scalable assets.

I'm using d3d_compiler47.dll 

the example automotive running under angle:
![image](https://user-images.githubusercontent.com/9283448/102768229-1d848b80-4381-11eb-9eec-09dbbfb459bf.png)

**Comment by uwerat** [comment]
What happens, when setting "export QSK_PREFER_RASTER=true" ?
( You could also set the QskSetup::PreferRasterForTextures flag in main )

Looks like multisampling does also not work in your environment ?

**Comment by ovenpasta** [comment]
I tried also that option, even manually setting `renderMode = Raster;` like for qt6... but no difference...

**Comment by ovenpasta** [comment]
By the way, the actual platform is under Virtual Box Guest. I will try under real machine, but in any case I would expect it to run also in VM :)
I'll check and report, also GL info

**Comment by ovenpasta** [comment]
```
qt.qpa.gl: Qt: Using EGL from libEGL
qt.qpa.gl: Qt: Using OpenGL ES 2.0 from libGLESv2
qt.qpa.gl: create Created EGL display 0xababf00 v 1 . 4
qt.scenegraph.general: windows render loop
qt.scenegraph.general: Using sg animation driver
qt.scenegraph.general: Animation Driver: using vsync: 16.67 ms
qt.qpa.gl: createPlatformOpenGLContext QSurfaceFormat(version 2.0, options QFlags<QSurfaceFormat::FormatOption>(), depthBufferSize 24, redBufferSize -1, greenBufferSize -1, blueBufferSize -1, alphaBufferSize -1, stencilBufferSize 8, samples 4, swapBehavior QSurfaceFormat::DoubleBuffer, swapInterval 1, colorSpace QSurfaceFormat::DefaultColorSpace, profile  QSurfaceFormat::NoProfile)
qt.scenegraph.general: opengl texture atlas dimensions: 2048x1024
qt.scenegraph.general: R/G/B/A Buffers:   5 6 5 0
qt.scenegraph.general: Depth Buffer:      24
qt.scenegraph.general: Stencil Buffer:    8
qt.scenegraph.general: Samples:           0
qt.scenegraph.general: GL_VENDOR:         Google Inc.
qt.scenegraph.general: GL_RENDERER:       ANGLE (VirtualBox Graphics Adapter (WDDM) Direct3D9Ex vs_3_0 ps_3_0)
qt.scenegraph.general: GL_VERSION:        OpenGL ES 2.0 (ANGLE 2.1.0.57ea533f79a7)
qt.scenegraph.general: GL_EXTENSIONS:     GL_ANGLE_client_arrays GL_ANGLE_framebuffer_blit GL_ANGLE_framebuffer_multisample GL_ANGLE_instanced_arrays GL_ANGLE_pack_reverse_row_order GL_ANGLE_program_cache_control GL_ANGLE_request_extension GL_ANGLE_robust_client_memory GL_ANGLE_texture_compression_dxt3 GL_ANGLE_texture_compression_dxt5 GL_ANGLE_texture_usage GL_ANGLE_translated_shader_source GL_CHROMIUM_bind_generates_resource GL_CHROMIUM_bind_uniform_location GL_CHROMIUM_color_buffer_float_rgb GL_CHROMIUM_color_buffer_float_rgba GL_CHROMIUM_copy_texture GL_CHROMIUM_sync_query GL_EXT_blend_minmax GL_EXT_color_buffer_half_float GL_EXT_debug_marker GL_EXT_frag_depth GL_EXT_occlusion_query_boolean GL_EXT_read_format_bgra GL_EXT_robustness GL_EXT_shader_texture_lod GL_EXT_texture_compression_dxt1 GL_EXT_texture_filter_anisotropic GL_EXT_texture_format_BGRA8888 GL_EXT_texture_storage GL_EXT_unpack_subimage GL_KHR_debug GL_NV_fence GL_NV_pack_subimage GL_OES_EGL_image GL_OES_EGL_image_external GL_OES_depth32 GL_OES_element_index_uint GL_OES_get_program_binary GL_OES_packed_depth_stencil GL_OES_rgb8_rgba8 GL_OES_standard_derivatives GL_OES_surfaceless_context GL_OES_texture_float GL_OES_texture_float_linear GL_OES_texture_half_float GL_OES_texture_half_float_linear GL_OES_texture_npot GL_OES_vertex_array_object
qt.scenegraph.general: Max Texture Size: 16384
qt.scenegraph.general: Debug context:    false
qt.qpa.gl: ~QWindowsEGLStaticContext Releasing EGL display  0xaba
```

**Comment by ovenpasta** [comment]
both calls to `glTexStorage2D` and `glTexSubImage2D` raise `GL_INVALID_OPERATION`
```

    if ( QOpenGLTexture::hasFeature( QOpenGLTexture::ImmutableStorage ) )
    {
        auto& ef = *context->extraFunctions();
        ef.glTexStorage2D( target, 1,
            QOpenGLTexture::RGBA8_UNorm, image.width(), image.height() );

        f.glTexSubImage2D( target, 0, 0, 0, image.width(), image.height(),
            QOpenGLTexture::RGBA, QOpenGLTexture::UInt8, image.constBits() );
    }
```

**Comment by ovenpasta** [comment]
[this is the cause of the GL_INVALID_OPERATION'](https://github.com/microsoft/angle/blob/6377e368358cd269e2273ad4cbb7a561f8a3a93b/src/libGLESv2/libGLESv2.cpp#L5095
)

so for ANGLE we need to use the following:
```
f.glTexImage2D( target, 0, GL_RGBA, image.width(), image.height(), 0,
                           GL_RGBA, GL_UNSIGNED_BYTE, image.constBits() );
```

I could't get it working for the ImmutableStorage option. Also, I don't know how to setup this only for ANGLE. In my case I've just hard-skipped the ImmutableStorage block and just use the fixed glTexImage2D.

**Comment by uwerat** [comment]
What happens, when replacing the opengl code by using QOpenGLTexture:

`static uint qskCreateTextureRaster(
    const QSize& size, QskTextureRenderer::PaintHelper* helper )
{
    QImage image( size, QImage::Format_RGBA8888_Premultiplied );
    image.fill( Qt::transparent );

    {
        QPainter painter( &image );
        helper->paint( &painter, size );
    }

    QOpenGLTexture texture( image );
    texture.bind();

    return texture.textureId();`

**Comment by ovenpasta** [comment]
If I replace the code with that, very weird things happen. First of all with QT_OPENGL=desktop I see black rectangles instead of the textures, in QT_OPENGL=angle I see some random things and after a bit black textures and also fonts disappear and become white rectangles. But even worse now neither the linux version works properly.

`QT_OPENGL=desktop
`![image](https://user-images.githubusercontent.com/9283448/102876457-82091e80-4445-11eb-8e5c-262df259c2b1.png)

`QT_OPENGL=angle
`![image](https://user-images.githubusercontent.com/9283448/102876366-61d95f80-4445-11eb-814b-e668b7d036fc.png)

after some window resize:
![image](https://user-images.githubusercontent.com/9283448/102876387-6736aa00-4445-11eb-99f3-1c94ad0e35d3.png)
