### ISSUE TITLE
Remove unnecessary null pointer checks

### ISSUE THREAD

**Issue by elfring** [uwerat/qskinny#90]
[An extra null pointer check is not needed in functions](https://isocpp.org/wiki/faq/freestore-mgmt#delete-handles-null "Do I need to check for null before delete p?") like the following.
- [QskHintAnimatorTable](https://github.com/uwerat/qskinny/blob/9f2cb6920dd119d433202fcec53674a3ce9baf57/src/controls/QskHintAnimator.cpp#L217 "Destructor for QskHintAnimatorTable")
- [QskSetup::cleanup](https://github.com/uwerat/qskinny/blob/bbbc02f1226ccb7b4d9d1ab0ea1a545d013a7517/src/controls/QskSetup.cpp#L145 "QskSetup::cleanup function")
- [QskSkin::declareSkinlet](https://github.com/uwerat/qskinny/blob/1a3058fad84149b8ec1225d97bd9c037673ae7dc/src/controls/QskSkin.cpp#L199 "QskSkin::declareSkinlet function")

**Comment by uwerat** [comment]
Sure, some code checker will spit out warnings. Fixed.

**Comment by elfring** [comment]
Thanks for [your small source code improvement](https://github.com/uwerat/qskinny/commit/f71bd4e359f4bbfcfa85ef5611709f819f31d3fe "Deletion of three redundant checks").

Do you know any other checking tools besides my source code analysis approach?

**Comment by uwerat** [comment]
clazy ( https://github.com/KDE/clazy ) can be very useful for finding specific Qt problems, that are not covered by the usual static code analyzers.
