### ISSUE TITLE
QskBusyIndicator

### ISSUE THREAD

**Issue by uwerat** [uwerat/qskinny#98]
A busy indicator is missing

**Comment by peter-ha** [comment]
It looks like most design systems use a radial indeterminate progress bar for a busy indicator these days:

- M3 (https://m3.material.io/components/progress-indicators/overview)
- F2 (https://learn.microsoft.com/en-us/windows/apps/design/controls/progress-controls)
- Goldman Sachs (https://design.gs.com/components/loading)
- VW (https://volkswagen.frontify.com/d/rzB71PwpjXgt/documentation#/components/loading)
- News Corp (https://www.newskit.co.uk/components/progress-indicator/)
- Cisco (https://www.figma.com/file/WHcIjwJZRBzxWAx4TSDhQHBT/Momentum.design?type=design&node-id=1191-204&mode=design&t=EoBSbyTb9Pc0vXvX-0)
- VMWare (https://www.figma.com/file/v2mkhzKQdhECXOx8BElgdA/Clarity-UI-Library---light-2.2.0?type=design&node-id=51-663&mode=design&t=9QZpucYzWVxHABJX-0)
- Chrome
- VirtualBox
- Figma


The notable exception to this is Apple, which still use a classic busy indicator:

- Apple (https://developer.apple.com/design/human-interface-guidelines/progress-indicators)

**Comment by uwerat** [comment]
A busy indicator can be implemented easily as composition from QskPopup and QskProgressRing. We should at least show how to do it in the examples
